# Generated by Django 6.0 on 2025-12-16 05:48

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForestDensityCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('canopy_pct', models.DecimalField(decimal_places=2, help_text='Canopy cover percentage for the cell (0-100).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('source', models.CharField(default='hansen_v1', help_text='Dataset/version identifier used to derive canopy cover.', max_length=64)),
                ('tile_id', models.CharField(blank=True, help_text='Optional tile or scene id to group cells by input product.', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Forest density cell',
                'verbose_name_plural': 'Forest density cells',
                'ordering': ['-updated_at'],
                'indexes': [django.contrib.postgres.indexes.GistIndex(fields=['geom'], name='forest_density_geom_gist'), models.Index(fields=['canopy_pct'], name='forest_density_canopy_pct_idx')],
            },
        ),
    ]
